package com.example.monkey_classification.presentation.util

import com.example.monkey_classification.R
import com.example.monkey_classification.model.Monkey

val monkeyList = listOf (
    Monkey(1, "Bald Ukari", R.drawable.bald_uakari, "The bald uakari or bald-headed uakari is a small New World monkey characterized by a very short tail; bright, crimson face; a bald head; and long coat. The bald uakari is restricted to várzea forests and other wooded habitats near water in the western Amazon of Brazil and Peru."),
    Monkey(2, "Emperor Tamarin", R.drawable.emperor_tamarin, "The emperor tamarin is a species of tamarin monkey allegedly named for its resemblance to the German emperor Wilhelm II. It lives in the north Brazilian states of Acre and Amazonas and the southwest Amazon Basin, in east Peru, north Bolivia"),
    Monkey(3, "Golden Monkey", R.drawable.golden_monkey, "The golden monkey (Cercopithecus mitis kandti) is a subspecies of the blue monkey.[2] It is an Old World monkey found in the Virunga volcanic mountains of Central Africa, including four national parks: Mgahinga, in south-west Uganda; Volcanoes, in north-west Rwanda; and Virunga and Kahuzi-Biéga, in the eastern Democratic Republic of Congo. It is restricted to highland forest, especially near bamboo."),
    Monkey(4, "Gray Langur", R.drawable.gray_langur, "Semnopithecus is a genus of Old World monkeys native to the Indian subcontinent, with all species with the exception of two being commonly known as gray langurs. Traditionally only one species Semnopithecus entellus was recognized, but since about 2001, additional species have been recognized."),
    Monkey(5, "Hamadryas Baboon", R.drawable.hamadryas_baboon, "The hamadryas baboon is a species of baboon within the Old World monkey family. It is the northernmost of all the baboons, being native to the Horn of Africa and the southwestern region of the Arabian Peninsula."),
    Monkey(6, "Mandril", R.drawable.mandrill, "The mandrill (Mandrillus sphinx) is a large Old World monkey native to west central Africa. It is one of the most colorful mammals in the world, with red and blue skin on its face and posterior. The species is sexually dimorphic, as males have a larger body, longer canine teeth and brighter coloring. It is the largest monkey in the world. Its closest living relative is the drill, with which it shares the genus Mandrillus. Both species were traditionally thought to be baboons, but further evidence has shown that they are more closely related to white-eyelid mangabeys."),
    Monkey(7, "Proboscis Monkey", R.drawable.proboscis_monkey, "The proboscis monkey or long-nosed monkey is an arboreal Old World monkey with an unusually large nose, a reddish-brown skin color and a long tail. It is endemic to the southeast Asian island of Borneo and is found mostly in mangrove forests and on the coastal areas of the island."),
    Monkey(8, "Red Howler", R.drawable.red_howler, "The Colombian red howler or Venezuelan red howler is a South American species of howler monkey, a type of New World monkey, found in the western Amazon Basin in Venezuela, Colombia, Ecuador, Peru and Brazil."),
    Monkey(9, "Vervet Monkey", R.drawable.vervet_monkey, "The vervet monkey, or simply vervet, is an Old World monkey of the family Cercopithecidae native to Africa. The term \"vervet\" is also used to refer to all the members of the genus Chlorocebus. The five distinct subspecies can be found mostly throughout Southern Africa, as well as some of the eastern countries."),
    Monkey(10, "White Faced Saki", R.drawable.white_faced_saki, "The white-faced saki, called the Guianan saki and the golden-faced saki, is a species of the New World saki monkey. They can be found in Brazil, French Guiana, Guyana, Suriname and Venezuela. This species lives in the understory and lower canopy of the forest, feeding mostly on fruits, nuts, seeds, and insects.")
)